FROM node:22-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN apk add --no-cache libc6-compat
RUN corepack enable

WORKDIR /workspace

COPY package.json pnpm-workspace.yaml turbo.json tsconfig.base.json .env.example ./
COPY apps ./apps
COPY services ./services
COPY packages ./packages

RUN pnpm install

CMD ["pnpm", "dev:services"]